version: "3.8"

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/kong.yml
    volumes:
      - /Users/sonthach/projects/miu-ea-project/kong.yml:/usr/local/kong/kong.yml:ro
    ports:
      - "8000:8000"  # Proxy port (HTTP)
      - "8443:8443"  # Proxy port (HTTPS)
      - "8001:8001"  # Admin API (HTTP)
      - "8444:8444"  # Admin API (HTTPS)