version: "3.8"

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/kong.yml
      - KONG_PLUGINS=bundled,jwt_parser
    volumes:
      - /Users/sonthach/projects/miu-ea-project/kong.yml:/usr/local/kong/kong.yml:ro
      - ./kong/custom_plugins/jwt_parser:/usr/local/share/lua/5.1/kong/plugins/jwt_parser
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  kafka:
    image: 'apache/kafka:3.9.0'
    ports:
      - '9092:9092'
  mysql-post:
    image: mysql:8.0
    container_name: mysql-post
    environment:
      MYSQL_DATABASE: cs544-post
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-post-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_DATABASE: cs544-user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  post-service:
    build: ./POST-SERV
    container_name: post-serv
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql-post
      MYSQL_DB: cs544-post
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8081
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql-post

  user-serv:
    build: ./USER-SERV
    container_name: user-serv
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-user
      MYSQL_DB: cs544-user
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql-user

volumes:
  mysql-post-data:
  mysql-user-data: