POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin1@miu.edu",
  "password": "password"
}

#####

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user1@miu.edu",
  "password": "password"
}