POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@miu.edu",
  "password": "password"
}

#####

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user1@miu.edu",
  "password": "password"
}