### Get all posts
GET http://localhost:8081/posts
Accept: application/json

### Get a post by ID
GET http://localhost:8081/posts/1
Accept: application/json

### Create a new post
POST http://localhost:8081/posts
Content-Type: application/json

{
  "title": "New Post",
  "content": "This is the content of the new post."
}

### Update a post
PUT http://localhost:8081/posts/1
Content-Type: application/json

{
  "title": "Updated Post",
  "content": "This is the updated content of the post."
}

### Delete a post
DELETE http://localhost:8081/posts/1
Accept: application/json